### ISSUE TITLE
Login Malfunctioning

### ISSUE THREAD

**Issue by AroPix** [3SnipeOfficial/3Snipe#4]
Doesn't matter if i use the login with a txt file or with typing it in in the console i can't login with the sniper.
![IMG_20200806_205431](https://user-images.githubusercontent.com/57004660/89571032-4c152600-d827-11ea-85c8-6d6f076698ac.jpg)
i also checked my login several times.

Edit: Also tried it with version 1.0.0 or 1.1.0

**Comment by tyTheDebugger** [comment]
Does it work now? You were probably rate limited.

**Comment by skyde-py** [comment]
i also have this problem

**Comment by xDxDxDxDxDxDxDxDxDxDxDxD** [comment]
I get the same error message

**Comment by tyTheDebugger** [comment]
Locked issue, will unlock if need arises.

**Comment by overestimate** [comment]
Should be fixed now, will reopen if still broken.
