### ISSUE TITLE
When opening 3Snipe it immediately closes pls help.

### ISSUE THREAD

**Issue by GodDamn-cmd** [3SnipeOfficial/3Snipe#9]
I click on the icon and sometimes I can get it open but only if I click like 200 times. When i check the activity of the software, it immediately opens then closes. It closes so fast that I cant even see it open. When i click it like 200 times and it opens, the window is all black and unusable. When the black window opens, and i click 1 or any key it will close immediately. I need to snipe a name really soon so please please answer fast. And when it opens i see a fatal error occured and alot of other text but it closes too fast.

**Comment by overestimate** [comment]
Read the docs at https://docs.3snipe.com/
